TekSan/Components/OpenCloseMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace TekSan.Components
{
    public class OpenCloseMenuViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public OpenCloseMenuViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }
        public IViewComponentResult Invoke(int id, bool trackChanges)
        {
            var propert = _manager.OpenCloseMenuService.GetOpenCloseMenuId(id, false);
            return View(propert);

        }
    }
}

TekSan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Teksan</title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    <!-- Favicons -->
    <link href="~/assets/img/favicon-48x48.png" rel="icon">
    <link rel="apple-touch-icon" sizes="180x180" href="~/assets/img/favicon-256x256.png">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    
    <!-- Main CSS File -->
    <link href="~/assets/css/main.css" rel="stylesheet">
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-PQKEY0LCFL">
    </script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-PQKEY0LCFL');
    </script>
 
</head>
<body>
    <header id="header" class="header d-flex align-items-center fixed-top">
        <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">

            <a asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="assets/img/logo.png" alt=""> -->
                <h1 class="sitename">TekSan<span>Tente</span></h1>
            </a>

            @await Component.InvokeAsync("OpenCloseMenu")

        </div>
    </header>
    <div class="container-fluid">
        <main role="main">
            @RenderBody()
           
        </main>
        
    </div>

    <footer id="footer" class="footer light-background">
       
        <div class="container">
            <div class="row gy-3">
                <div class="col-lg-3 col-md-6 d-flex">
                    <i class="bi bi-geo-alt icon"></i>
                    <div class="address">
                        <h3>Address</h3>
                        <a href="https://www.google.com/maps/search/?api=1&query=40.9997444,28.7038002"
                           target="_blank" rel="noopener noreferrer"
                           aria-label="Haritada görüntüle: 40°59'59.1&quot;N 28°42'13.7&quot;E">
                            TekSan Tente
                        </a>
                        <p></p>
                    </div>

                </div>

                <div class="col-lg-3 col-md-6 d-flex">
                    <i class="bi bi-telephone icon"></i>
                    <div>
                        <h4>İletişim</h4>
                        <p>
                            <strong>WhatsApp:</strong> <a href="https://wa.me/905333807444" target="_blank"
                                                          rel="noopener">WhatsApp'tan Fiyat Al</a><br>
                            <strong>Telefon:</strong> <a href="tel:905421590144">+90542 159 01 44</a><br>
                            <strong>Telefon:</strong> <a href="tel:02124237444">0212 423 74 44</a><br>
                            <strong>E-mail:</strong> <a href="mailto:teksanpergola@gmail.com">teksnapergola@gmail.com</a><br>
                        </p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 d-flex">
                    <i class="bi bi-clock icon"></i>
                    <div>
                        <h4>Açılış Saatleri</h4>
                        <p>
                            <strong>Pazartesi-Cumartesi:</strong> <span>8:00 - 18:00</span><br>
                            <strong>Pazar</strong>: <span>Kapalı</span>
                        </p>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6">
                    <h4>Bizi takip edin</h4>
                    <div class="social-links d-flex">
                        <a href="#" class="twitter"><i class="bi bi-twitter-x"></i></a>
                        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                    </div>
                </div>

            </div>
        </div>
        <div class="fab-container">
            <div class="fab"><i class="bi bi-whatsapp"></i></div>
            <ul class="fab-options">
                <li><a href="https://wa.me/905333807444" target="_blank"><i class="bi bi-whatsapp"></i></a></li>
                <li><a href="tel:02124237444"><i class="bi bi-telephone"></i></a></li>
                <li><a href="mailto:teksanpergola@gmail.com"><i class="bi bi-envelope"></i></a></li>
                <li><a href="https://www.google.com/maps/search/?api=1&query=40.9997444,28.7038002" target="_blank">
                          <i class="bi bi-geo-alt"></i>
                     </a>

            </ul>
        </div>


        <div class="container copyright text-center mt-4">
            <p>
                © <span>Telif Hakkı</span> <strong class="px-1 sitename">TekSanTente</strong> <span>
                    Tüm Hakları
                    Saklıdır.
                </span>
            </p>
            <div class="credits">
            </div>
        </div>




    </footer>
    <!-- Scroll Top -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center">
        <i class="bi bi-arrow-up-short"></i>
    </a>

    <!-- Preloader -->
    <div id="preloader"></div>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Main JS File -->
    <script src="~/assets/js/main.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>